# Generated by Django 5.2.7 on 2025-10-03 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery')),
                ('title', models.CharField(default='no title', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Memorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='memorial')),
                ('date_of_death', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.CharField(blank=True, max_length=200, null=True)),
                ('posters', models.ImageField(blank=True, null=True, upload_to='notice_posters/')),
            ],
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('job', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=15)),
                ('position', models.CharField(default='Parent', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='committee')),
                ('place', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sub_name', models.CharField(max_length=150)),
                ('place', models.CharField(max_length=100)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='school-images')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='school-images')),
                ('adress', models.TextField()),
                ('phone_number', models.CharField(max_length=12)),
                ('history', models.TextField()),
                ('educational_board', models.CharField(blank=True, max_length=200, null=True)),
                ('reg_number', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'School Detail',
                'verbose_name_plural': 'School Details',
            },
        ),
        migrations.CreateModel(
            name='TopScorer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std', models.CharField(max_length=20)),
                ('exam_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('first_father_name', models.CharField(max_length=50)),
                ('first_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('second_name', models.CharField(max_length=50)),
                ('second_father_name', models.CharField(max_length=50)),
                ('second_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('third_name', models.CharField(max_length=50)),
                ('third_father_name', models.CharField(max_length=50)),
                ('third_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'ordering': ['std', 'exam_name'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=12)),
                ('job', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('relation', models.CharField(max_length=20)),
                ('martial_status', models.CharField(blank=True, max_length=50, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='dashboard.parents')),
            ],
        ),
    ]
