# Generated by Django 5.2.7 on 2025-10-03 16:39

import datetime
import django.db.models.deletion
import django.utils.timezone
import teachers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff_Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='notification')),
                ('voice', models.FileField(blank=True, null=True, upload_to='voice_notifications')),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField(default=teachers.models.get_current_time)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('blood_grp', models.CharField(max_length=10)),
                ('msr_no', models.CharField(max_length=20)),
                ('salary', models.CharField(max_length=10)),
                ('joined_date', models.DateField()),
                ('islamic_qualification', models.CharField(max_length=50)),
                ('academic_qualification', models.CharField(max_length=50)),
                ('other_occupation', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_no', models.CharField(max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='teachers')),
                ('place', models.CharField(max_length=50)),
                ('reg_no', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Staff_NotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='teachers.staff_notification')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='read_notifications', to='teachers.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Replay_Staff_Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replay', models.TextField()),
                ('replay_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replay_status', to='teachers.staff_notification')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('session', models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='present', max_length=10)),
                ('attendance_comments', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='teachers.teacher')),
            ],
            options={
                'ordering': ['-date', 'session'],
                'unique_together': {('teacher', 'date', 'session')},
            },
        ),
    ]
