from django.urls import path
from .views import (principal_login,get_csrf_token,principal_logout,
                    edit_teacher_profile,add_student,
                    get_all_teachers_attendance,
                    get_all_teachers_attendance_summary,
                    mark_teacher_attendance,get_all_student_attendance,
                    get_teacher_attendance_by_date_session,
                   mark_attendance,get_all_student_progress,
                   get_terms,get_notification_viewer,
                   create_progress,create_notification_staff,
                   get_notification,delete_notification,get_notification_replays,
                   create_notification_students,edit_std,
                   get_public_notification,get_daily_routine,
                   get_public_notification_viewer,add_notice,
                   delete_public_notification,create_standard,get_all_teachers,
                   add_gallery,gallery_delete,notice_delete,get_all_classs_with_details,
                   get_all_my_stds,get_all_teachers_attendance_summary,get_subjects_by_class_id,
                   get_attendance_by_class,get_class_teacher,remove_students,pass_student,student_info,edit_students_profile,mark_class_completed,
                   get_parents,get_members_by_parents,add_parents,get_students_attendance_by_date

                    )


urlpatterns = [
    path('csrf-token/',get_csrf_token,name='csrf-token'),
    path('login/',principal_login,name='principal-login'),
    path('logout/',principal_logout,name='principal-logout'),
    path('all-teacher/',get_all_teachers ,name='all-teachr'),
    path('edit-teacher-profile/<int:teacher_id>/',edit_teacher_profile,name='edit-tchr-profile'),
    path('add-student/',add_student,name='add-student'),
    path('all-tchr-attendance/<int:teacher_id>/', get_all_teachers_attendance, name='teachers_attendance'),
    path('all-teachers-attendance-summery/',get_all_teachers_attendance_summary,name='teacher-attendance-summery'),
    path('mark-teachers-attendance/',mark_teacher_attendance,name='mark-tchr-attendance'),
    path('teachers-attendance-by-date/',get_teacher_attendance_by_date_session,name='mark-tchr-attendance'),
    path('students-attendance-by-date/<int:class_id>/',get_students_attendance_by_date,name='get-std-attendance'),
    path('mark-all-std-attendnace/',mark_attendance,name='mark-std-attendance'),
    path('get-student-progress/<int:student_id>/', get_all_student_progress, name='all_students_progress'),
    path('create-progress-report/', create_progress, name='create_progress_report'),
    path('terms/', get_terms, name='terms'),
    path('create-notification/', create_notification_staff, name='create-notification'),
    path('get-notification/', get_notification, name='get-notification'),
    path('delete-notification/<int:notification_id>/', delete_notification ,name='get-notification'),
    path('get-viewer/<int:notifification_id>/', get_notification_viewer ,name='get-viewer'),
    path('get-replay/<int:notification_id>/', get_notification_replays,name='get-replay'),
    path('create-class-notification/', create_notification_students, name='create-class-notification'),
    path('get-students-viewer/<int:notifification_id>/',get_public_notification_viewer  ,name='get-viewer'),
    path('get-public-notifi/',get_public_notification ,name='public-noti'),
    path('delete-std-notification/<int:notification_id>/',delete_public_notification ,name='delete-std-noti'),
    path('add-standard/',create_standard ,name='add-std'),
    path('edit-standard/<int:class_id>/', edit_std,name='edit-std'),
    path('get-daily-routine/<int:student_id>/', get_daily_routine,name='daily-routine'),
    path('add-notice/',add_notice ,name='add-standard'),
    path('add-gallery/',add_gallery,name='add-gallery'),
    path('delete-gallery/<int:image_id>/',gallery_delete,name='delete-gallery'),
    path('delete-notice/<int:image_id>/',notice_delete,name='delete-notice'),
    path('add-gallery/',add_gallery,name='add-gallery'),
    path('get-class-with-stds/',get_all_classs_with_details,name='all-class'),
    path('get-my-stds/',get_all_my_stds,name='my-std'),
    path('class-subjects/<int:class_id>/',get_subjects_by_class_id,name='subjects'),
    path('get-attendnace-by-class/<int:class_id>/', get_attendance_by_class, name='attendance-class'),
    path('class-teacher/<int:class_id>/', get_class_teacher, name='get_student_progress'),
    path('mark-class-status/<int:class_id>/', mark_class_completed, name='class-status'),
    path('remove-student/<int:student_id>/',remove_students, name='remove-student'),
    path('pass-student/<int:student_id>/',pass_student, name='pass-student'),
    path('all-students-attendance/', get_all_student_attendance, name='students_attendance'),
    path('all-class-with-std-info/',student_info, name='students-info'),
    path('parents/',get_parents, name='parents'),
    path('get-members/<int:parent_id>/',get_members_by_parents, name='members'),
    path('add-parents/', add_parents, name='add_parents'),
    path('edit-student-profile/<int:student_id>/', edit_students_profile, name='edit-info')


]
