from django.urls import path
from .views import (management_login,logout_view,add_teacher,delete_teacher,edit_teacher_profile,
                    add_management,delete_management,get_all_classs_with_students,
                    add_principal,get_principal,delete_principal,get_teacher_attendance_by_date_session,
                    add_gallery,add_notice,notice_delete,gallery_delete,mark_teacher_attendance,
                    get_csrf_token,get_all_teachers_attendance_summary,get_all_student_attendance,
                    get_all_teachers_attendance,get_all_student_progress,get_management,get_all_teachers_with_data,add_memorial,get_members_by_parents,
                    get_attendance_by_class,get_class_teacher,get_parents,add_parents
                    )

urlpatterns = [
    path('csrf-token/',get_csrf_token,name='csrf-token'),
    path('login/',management_login,name='authority-login'),
    path('logout/',logout_view,name='authority-logout'),
    path('all-teachers/',get_all_teachers_with_data,name='all-teachers'),
    path('all-class-with-stds/',get_all_classs_with_students,name='all-std-class'),
    path('add-management/',add_management,name='add-management'),
    path('get-management/',get_management,name='get-management'),
    path('delete-management/<int:management_id>/',delete_management,name='delete-management'),
    path('add-new-teacher/',add_teacher,name='add-teacher'),
    path('add-new-principal/',add_principal,name='add-principal'),
    path('get-principal/',get_principal,name='get-principal'),
    path('delete-teacher/<int:teacher_id>/',delete_teacher,name='delete-teacher'),
    path('delete-principal/<int:principal_id>/',delete_principal,name='delete-teacher'),
    path('add-notice/',add_notice,name='add-notice'),
    path('add-gallery/',add_gallery,name='add-gallery'),
    path('mark-teachers-attendance/',mark_teacher_attendance,name='mark-tchr-attendance'),
    path('delete-notice/<int:image_id>/',notice_delete,name='delete-notice'),
    path('delete-gallery/<int:image_id>/',gallery_delete,name='delete-gallery'),
    path('get-attendnace-by-date-session/',get_teacher_attendance_by_date_session,name='mark-tchr-attendance'),
    path('all-teachers-attendance-summery/',get_all_teachers_attendance_summary,name='teacher-attendance-summery'),
    path('all-tchr-attendance/<int:teacher_id>/', get_all_teachers_attendance, name='teachers_attendance'),
    path('get-student-progress/<int:student_id>/', get_all_student_progress, name='all_students_progress'),
    path('edit-teacher-profile/<int:teacher_id>/',edit_teacher_profile,name='edit-tchr-profile'),
    path('get-attendnace-by-class/<int:class_id>/', get_attendance_by_class, name='attendance-class'),
    path('class-teacher/<int:class_id>/', get_class_teacher, name='get_student_progress'),
    path('all-students-attendance/', get_all_student_attendance, name='students_attendance'),
    path('add-memorial/', add_memorial, name='students_attendance'),
    path('parents/',get_parents, name='parents'),
    path('get-members/<int:parent_id>/',get_members_by_parents, name='members'),
    path('add-parents/', add_parents, name='add_parents'),
]
