# Generated by Django 5.2.7 on 2025-10-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=15)),
                ('phone_no', models.CharField(max_length=12)),
                ('image', models.ImageField(blank=True, null=True, upload_to='principal')),
                ('place', models.CharField(max_length=50)),
                ('reg_no', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
