# Generated by Django 5.2.7 on 2025-10-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principal',
            name='phone_no',
            field=models.CharField(max_length=20),
        ),
    ]
