# Generated by Django 5.2.7 on 2025-10-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_alter_principal_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principal',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='principal',
            name='phone_no',
            field=models.CharField(max_length=12),
        ),
    ]
