# Generated by Django 5.2.7 on 2025-10-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=10)),
                ('position', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='committee')),
                ('reg_no', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
