# Generated by Django 5.2.7 on 2025-10-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='reg_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
